DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS cars;
DROP TABLE IF EXISTS headbands;
DROP TABLE IF EXISTS spirits;
DROP TABLE IF EXISTS entrees;


CREATE TABLE orders (
    id BIGINT PRIMARY KEY NOT NULL,
    quantity_of_items BIGINT
);

CREATE TABLE cars (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    make VARCHAR(128) NOT NULL,
    model VARCHAR(128) NOT NULL,
    year BIGINT NOT NULL
);

CREATE TABLE headbands (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    color VARCHAR(128) NOT NULL,
    size VARCHAR(128) NOT NULL
);

CREATE TABLE spirits (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    region VARCHAR(128) NOT NULL,
    abv VARCHAR(128) NOT NULL
);

CREATE TABLE entrees (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    price FLOAT NOT NULL,
    is_good BOOLEAN NOT NULL
);